#!/bin/bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# Install oh my zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# find the installers and run them iteratively
installers=()
while IFS=  read -r -d $'\0'; do
  installers+=("$REPLY")
done < <(find . -name install.sh -print0)

for installer in "${installers[@]}"; do
  echo "Running ${installer}"
  sh -c ${installer}
done
